const Data = [
  {
    id: 1,
    category: "Ara Sıcaklar",
    name: "Kaşarlı Izgara Mantar",
    price: 75,
    symbol: "₺",
    Image: "assets/FoodPictures/kasarlı-ızgara-mantar.jpg",
    description:
      "Kaşarlı ızgara mantar, taze mantarların içi kaşar peyniriyle dolu bir dansıdır. Izgara teline atılan her adımda, mantarların tınlamasıyla birlikte peynirin eriyip kızarmasıyla lezzet rüyası gerçekleşir. Sağlıklı ve hızlı bir seçenek olan bu atıştırmalık, sofralarınıza lezzet ve keyif getirir.",
  },
  {
    id: 2,
    category: "Ara Sıcaklar",
    name: "Patates Kızartması",
    price: 75,
    symbol: "₺",
    Image: "assets/FoodPictures/patates_cipsi-560302649.jpg",
    description:
      "Patates kızartması, altın rengindeki çıtır çıtır dilimlerle damaklarda unutulmaz bir lezzet serüveni sunar. Her lokmada çıkan hafif çıtırtı, içindeki yumuşaklıkla buluşur ve her ısırık, doyumsuz bir keyif sunar. Özellikle fast food kültürünün vazgeçilmezi olan patates kızartması, sıcak, tuzlu ve eşsiz bir lezzet sunarak her anınıza tat katıyor.",
  },
  {
    id: 3,
    category: "Ara Sıcaklar",
    name: "Hellim Şiş",
    price: 75,
    symbol: "₺",
    Image: "assets/FoodPictures/kasarlı-ızgara-mantar.jpg",
    description:
      "Hellim peyniri, ızgarada nar gibi kızarırken şişe geçirilerek sunulan hellim şiş, Akdeniz'in eşsiz lezzetlerinden biridir. Tuzlu ve yoğun hellim peynirinin ızgarada çıtır çıtır olması, içindeki aromayı ve yumuşaklığı ortaya çıkarır. Hellim şiş, hem atıştırmalık hem de ana yemek olarak tercih edilen, doyurucu ve keyifli bir seçenektir. Akşamüstü sohbetlerinden mangal partilerine kadar her anı lezzetlendirir.",
  },
  {
    id: 4,
    category: "Ara Sıcaklar",
    name: "Kıbrıs Pastırması",
    price: 75,
    symbol: "₺",
    Image: "assets/FoodPictures/kibris_pastirmasi-91d6a7c6-1809433242.jpg",
    description:
      "Kıbrıs pastırması, özenle marine edilip kurutulan etin ardından baharatlarla harmanlanarak oluşturulan eşsiz bir tat sunar. İnce dilimler halinde sunulan bu pastırma, özgün lezzeti ve tuzlu-kırmızı biber karışımının aromasıyla damaklarda unutulmaz bir iz bırakır. Kahvaltılardan sandviçlere, mezelerden ana yemeklere kadar geniş bir yelpazede kullanılan Kıbrıs pastırması, her diliminde bir öykü taşır.",
  },
  {
    id: 5,
    category: "Ara Sıcaklar",
    name: "Kabak Mücver",
    price: 75,
    symbol: "₺",
    Image: "assets/FoodPictures/kasarlı-ızgara-mantar.jpg",
    description:
      "Kabak mücver, taze kabakların rendelenip karıştırıldığı, baharatlarla zenginleştirilen ve kızartılan nefis bir tariftir. Hafif ve gevrek dış kabuğuyla çıtır çıtır, içindeki kabak dolgusuyla ise yumuşacık bir deneyim sunar. Hem ana yemek olarak hem de atıştırmalık olarak tercih edilen kabak mücver, sofralara renk, lezzet ve sağlık katıyor.",
  },
  {
    id: 6,
    category: "Ara Sıcaklar",
    name: "Yaprak Ciğer",
    price: 100,
    symbol: "₺",
    Image: "assets/FoodPictures/kasarlı-ızgara-mantar.jpg",
    description:
      "Kaşarlı ızgara mantar, taze mantarların içi kaşar peyniriyle dolu bir dansıdır. Izgara teline atılan her adımda, mantarların tınlamasıyla birlikte peynirin eriyip kızarmasıyla lezzet rüyası gerçekleşir. Sağlıklı ve hızlı bir seçenek olan bu atıştırmalık, sofralarınıza lezzet ve keyif getirir.",
  },
  {
    id: 7,
    category: "Ara Sıcaklar",
    name: "Günün Çorbası",
    price: 70,
    symbol: "₺",
    Image: "assets/FoodPictures/gunun_corbasi-e5087baa-3301148691.jpg",
    description: "Güne Göre Değişir",
  },
  {
    id: 8,
    category: "Salatalar",
    name: "Çoban SAlata",
    price: 70,
    symbol: "₺",
    Image: "assets/FoodPictures/cobansalata.webp",
    description:
      "Çoban salatası, Akdeniz mutfağının sevilen ve taze malzemelerin harika bir uyumuyla oluşturulan bir meze veya yan yemektir. Bu lezzetli salata, taze sebzelerin zenginliğiyle öne çıkar. Domates, salatalık, yeşil biber, soğan gibi sebzeler doğranır ve zeytinyağı, limon suyu, tuz ve baharatlarla harmanlanır.",
  },
  {
    id: 9,
    category: "Salatalar",
    name: "Gavurdağı Salatası",
    price: 80,
    symbol: "₺",
    Image: "assets/FoodPictures/gavurdagısalata.webp",
    description:
      "Geleneksel tarifine göre, ince doğranmış domates, salatalık, yeşil biber, soğan gibi sebzeler zeytinyağı, nar ekşisi, tuz ve baharatlarla karıştırılarak hazırlanır. Üzerine bolca nar taneleri serpilerek zenginleştirilir. Nar ekşisi ve nar taneleri, salatanın tat ve renk dengesine farklı bir boyut katar.",
  },
  {
    id: 10,
    category: "Salatalar",
    name: "Hellimli Salata",
    price: 130,
    symbol: "₺",
    Image: "assets/FoodPictures/hellimli salata.webp",
    description:
      "Akdeniz mutfağının lezzetli ve sağlıklı bir örneğidir. Ana malzemesi hellim peyniri olan bu salata, taze sebzeler ve zeytinyağı ile bir araya getirilerek hazırlanır. Salatanın temel malzemeleri genellikle domates, salatalık, yeşil biber, kırmızı soğan gibi sebzelerdir. Bunlar doğranıp karıştırılır ve üzerine küp şeklinde doğranmış hellim peyniri eklenir.",
  },
  {
    id: 11,
    category: "Salatalar",
    name: "Kasık Salata",
    price: 55,
    symbol: "₺",
    Image: "assets/FoodPictures/kasıksalata.webp",
    description:
      "Temel malzemeleri domates, salatalık, yeşil biber, taze soğan, maydanoz gibi taze sebzelerdir. Bu sebzeler ince ince doğranır ve karıştırma kabına alınır. Üzerine zeytinyağı, limon suyu, tuz, nar ekşisi gibi malzemeler eklenerek tatlandırılır. Ayrıca bazen sumak da kullanılarak ekstra bir lezzet katılır.",
  },
  {
    id: 12,
    category: "Salatalar",
    name: "Mevsim Salata",
    price: 70,
    symbol: "₺",
    Image: "",
    description:
      "çeşitli yeşil yapraklar, domates dilimleri, salatalık halkaları, havuç rendesi ve renkli biberler gibi çeşitli sebzelerden oluşur. Bunun yanı sıra taze roka, marul, taze soğan veya dereotu gibi otlar da eklenerek zenginleştirilir.",
  },
  {
    id: 13,
    category: "Mezeler",
    name: "Kavun",
    price: 55,
    symbol: "₺",
    Image: "",
    description:
      "Bu serinletici meyveyi lezzetli kebaplarla bir araya getirerek unutulmaz bir deneyim sunuyor. Kavunun taze ve tatlı tadı, kebapların zengin aromalarıyla buluşuyor, misafirlerine damaklarına hitap eden eşsiz bir deneyim sunuyor.",
  },
  {
    id: 14,
    category: "Mezeler",
    name: "Havuç Tarator",
    price: 40,
    symbol: "₺",
    Image: "",
    description:
      "Geleneksel tarator lezzetini modern ve yenilikçi bir yaklaşımla sunarak damakları şenlendiriyor. Havuçun doğal tatlılığı ve taratorun ferahlatıcı dokusu, bu restoranda buluşuyor ve unutulmaz bir yemek deneyimi yaratıyor.",
  },
  {
    id: 15,
    category: "Mezeler",
    name: "Acılı Ezme",
    price: 55,
    symbol: "₺",
    Image: "",
    description:
      "Acının ve baharatların zengin dünyasını lezzetli malzemelerle buluşturan bir mezeyi temsil ediyor. Baharatların ve taze sebzelerin özenle hazırlandığı bu ezme, hem göz hem de damak zevkine hitap ediyor.",
  },
  {
    id: 16,
    category: "Mezeler",
    name: "Çakısdez",
    price: 40,
    symbol: "₺",
    Image: "",
    description:
      "zengin aroması ve taze dokusuyla kebapların yanında tüketildiğinde damakta hoş bir denge yaratır.",
  },
  {
    id: 17,
    category: "Mezeler",
    name: "Köpoğlu",
    price: 55,
    symbol: "₺",
    Image: "",
    description:
      "Köpoğlu, yöresel tatlardan ilham alarak hazırlanan, közlenmiş patlıcan, domates ve yeşil biberin harmanlandığı nefis bir seçenektir.",
  },
  {
    id: 18,
    category: "Mezeler",
    name: "Yoğurtlu Patlıcan",
    price: 55,
    symbol: "₺",
    Image: "",
    description:
      "Bu meze, közlenmiş patlıcanların yoğurtla buluştuğu nefis bir lezzettir. Patlıcanların közlenmiş tadıyla yoğurdun hafifliği bir araya gelerek mükemmel bir denge sunar.",
  },
  {
    id: 19,
    category: "Mezeler",
    name: "Atom",
    price: 50,
    symbol: "₺",
    Image: "",
    description: "Süzme yoğurt, acı biber, sarımsak",
  },
  {
    id: 20,
    category: "Mezeler",
    name: "Humus",
    price: 50,
    symbol: "₺",
    Image: "",
    description:
      "Ana malzemesi nohut olan humus, tahin (susam ezmesi), zeytinyağı, limon suyu, sarımsak ve baharatlarla karıştırılarak yapılan bir sostur.",
  },
  {
    id: 21,
    category: "Mezeler",
    name: "Ezine Peyniri",
    price: 80,
    symbol: "₺",
    Image: "",
    description:
      "Üzerine zeytinyağı, taze otlar, baharatlar ve bazen pul biber eklenerek zenginleştirilir.",
  },
  {
    id: 22,
    category: "Mezeler",
    name: "Cacık",
    price: 40,
    symbol: "₺",
    Image: "",
    description:
      "Özellikle kebapla bir araya geldiğinde lezzetini daha da artıran bu serinletici meze, yoğurt, salatalık, nane ve sarımsak gibi malzemelerin mükemmel bir uyumla buluşmasıyla hazırlanır.",
  },
  {
    id: 23,
    category: "Mezeler",
    name: "Haydari",
    price: 40,
    symbol: "₺",
    Image: "",
    description:
      "yoğurtlu ve ferahlatıcı tadıyla kebap çeşitleriyle harika bir uyum sağlar.",
  },
  {
    id: 24,
    category: "Mezeler",
    name: "Süzme Yoğurt",
    price: 50,
    symbol: "₺",
    Image: "",
    description:
      "Sofranın vazgeçilmez tamamlayıcılarından biri olan süzme yoğurt, hem lezzetiyle hem de sağlık avantajlarıyla sofraları süslüyor. Kebapların yanında sunulan süzme yoğurt, hem hafif bir tat sunar hem de yoğun lezzetiyle damakları şenlendirir.",
  },
  {
    id: 25,
    category: "Fırın",
    name: "Fındık Lahmacun",
    price: 20,
    symbol: "₺",
    Image: "",
    description:
      "İncecik açılan hamurun üzerine serpiştirilen lezzetli kıymalı harcın yanı sıra bolca fındıkla zenginleşen fındık lahmacun, hem görsel bir şölen sunuyor hem de farklı tatları denemek isteyen misafirlerimize özel bir deneyim sunuyor.",
  },
  {
    id: 26,
    category: "Fırın",
    name: "Kavurma Kaşarlı",
    price: 190,
    symbol: "₺",
    Image: "",
    description:
      "Kebap restoranımızın özel menüsünde yer alan kavurma kaşarlı, etin eşsiz lezzetini kaşar peynirinin mükemmel uyumuyla buluşturuyor. Kavurmanın lezzetli ve doyurucu tadı, kaşar peynirinin kremalı dokusuyla buluşarak damaklarda unutulmaz bir iz bırakıyor.",
  },
  {
    id: 27,
    category: "Fırın",
    name: "Karışık Pide",
    price: 185,
    symbol: "₺",
    Image: "",
    description:
      "farklı lezzetleri bir araya getirerek damaklarınıza unutulmaz bir şölen sunuyor. Hamurunun enfes lezzetiyle hazırlanan karışık pide, çeşitli malzemelerle zenginleştirilerek her lokmada farklı tatlarla buluşmanızı sağlıyor.",
  },
  {
    id: 28,
    category: "Fırın",
    name: "Kaşarlı Pastırmalı Pide",
    price: 180,
    symbol: "₺",
    Image: "",
    description:
      "kaşarlı pastırmalı pide, geleneksel lezzetleri modern bir yaklaşımla buluşturuyor. Hamurunun enfes dokusu, içerisindeki lezzetli malzemelerle bir araya gelerek damaklarda unutulmaz bir iz bırakıyor.",
  },
  {
    id: 29,
    category: "Fırın",
    name: "Kaşarlı Pide",
    price: 130,
    symbol: "₺",
    Image: "",
    description:
      "Kaşarlı pide, sıcacık ve kıvamında hamuru ile her ısırıkta ağızda eriyor. Kaşar peynirinin lezzeti, hamurun nefis dokusuyla buluşuyor ve ortaya doyumsuz bir lezzet çıkıyor. Yanında servis edilen taze yeşillikler, pidenin lezzetini daha da zenginleştiriyor.",
  },
  {
    id: 30,
    category: "Fırın",
    name: "Hellimli Pide",
    price: 130,
    symbol: "₺",
    Image: "",
    description:
      "İncecik açılmış hamurun üzerine taze hellim peyniri yerleştirilerek hazırlanan bu pide, özel fırınlarda pişirilerek mükemmel bir kıvama ulaşıyor. Fırından çıkan pidenin enfes kokusu ve görüntüsü, lezzetini önceden hissettiriyor.",
  },
  {
    id: 31,
    category: "Fırın",
    name: "Kuşbaşılı Pide",
    price: 155,
    symbol: "₺",
    Image: "",
    description:
      "İnce hamurun üzerine özenle yerleştirilen kuşbaşı etleri, baharatlarla zenginleştirilerek özel bir pişirme yöntemiyle hazırlanıyor. Fırından çıktığında etlerin aroması tüm mekânı sarmalarken, pidenin üzerine eklenen taze yeşilliklerle görsel bir şölen oluşturuluyor.",
  },
  {
    id: 32,
    category: "Fırın",
    name: "Kıymalı Pide",
    price: 130,
    symbol: "₺",
    Image: "",
    description:
      "Kıymalı pide, lezzetli kıyma, soğan ve baharatların özenle karıştırılmasıyla hazırlanan özel bir harçla yapılır. Hamurun üzerine yayılan bu harç, fırında pişirildiğinde muhteşem bir aroma ve lezzet patlaması yaratır. Üzerine eklenen taze yeşilliklerle renklendirilen kıymalı pide, hem görsel bir şölen sunar hem de damakları şenlendirir.",
  },
  {
    id: 33,
    category: "Fırın",
    name: "Glutensiz Lahmacun",
    price: 60,
    symbol: "₺",
    Image: "",
    description:
      "Glutensiz lahmacun, özel olarak hazırlanan glutensiz hamurun üzerine, lezzetli lahmacun harcıyla buluşuyor. Lahmacunun geleneksel lezzetini koruyarak, özel bir hamur alternatifi kullanılarak hazırlanan bu versiyon, glutensiz beslenmeyi tercih eden misafirlerimizin de lezzetli bir deneyim yaşamasına olanak tanıyor.",
  },
  {
    id: 34,
    category: "Fırın",
    name: "Lahmacun",
    price: 46,
    symbol: "₺",
    Image: "",
    description:
      "Lahmacun, kıyma, soğan, biber salçası ve baharatların harmanlanmasıyla oluşturulan iç harcın hamur üzerine yayılmasıyla hazırlanır. Hamurun üzerine sürülen harcın ardından fırınlanmasıyla ortaya çıkan lahmacun, sıcak ve taze servis edildiğinde enfes bir lezzet sunar.",
  },
  {
    id: 35,
    category: "Kebaplar",
    name: "Beyti Sarma",
    price: 180,
    symbol: "₺",
    Image: "",
    description: "200gr",
  },
  {
    id: 36,
    category: "Kebaplar",
    name: "Kuzu Kavurma",
    price: 310,
    symbol: "₺",
    Image: "",
    description: "300gr",
  },
  {
    id: 37,
    category: "Kebaplar",
    name: "Ali Nazik",
    price: 230,
    symbol: "₺",
    Image: "",
    description: "200gr",
  },
  {
    id: 38,
    category: "Kebaplar",
    name: "Domates Kebabı",
    price: 210,
    symbol: "₺",
    Image: "",
    description: "200gr",
  },
  {
    id: 39,
    category: "Kebaplar",
    name: "Patlıcan Kebabı",
    price: 210,
    symbol: "₺",
    Image: "",
    description: "200gr",
  },
  {
    id: 40,
    category: "Kebaplar",
    name: "Afitap Karışık",
    price: 575,
    symbol: "₺",
    Image: "",
    description: "740gr",
  },
  {
    id: 41,
    category: "Kebaplar",
    name: "Patlıcan Kebabı",
    price: 210,
    symbol: "₺",
    Image: "",
    description: "200gr",
  },
  {
    id: 42,
    category: "Kebaplar",
    name: "Karışık Kebap",
    price: 340,
    symbol: "₺",
    Image: "",
    description: "400gr",
  },
  {
    id: 43,
    category: "Kebaplar",
    name: "Kuzu Ciğer",
    price: 210,
    symbol: "₺",
    Image: "",
    description: "200gr",
  },
  {
    id: 44,
    category: "Kebaplar",
    name: "Kuzu Pirzola",
    price: 270,
    symbol: "₺",
    Image: "",
    description: "200gr",
  },
  {
    id: 45,
    category: "Kebaplar",
    name: "Adana Kebap",
    price: 200,
    symbol: "₺",
    Image: "",
    description: "200gr",
  },
  {
    id: 46,
    category: "Kebaplar",
    name: "Tavuk Pirzola",
    price: 190,
    symbol: "₺",
    Image: "",
    description: "330gr",
  },
  {
    id: 47,
    category: "Kebaplar",
    name: "Tavuk Şiş",
    price: 190,
    symbol: "₺",
    Image: "",
    description: "200gr",
  },
  {
    id: 48,
    category: "Kebaplar",
    name: "Izgara Kanat",
    price: 200,
    symbol: "₺",
    Image: "",
    description: "280gr",
  },
  {
    id: 49,
    category: "Kebaplar",
    name: "Şeftali Kebabı",
    price: 200,
    symbol: "₺",
    Image: "",
    description: "275gr",
  },
  {
    id: 50,
    category: "Kebaplar",
    name: "Afitap Köfde",
    price: 185,
    symbol: "₺",
    Image: "",
    description: "250gr",
  },
  {
    id: 51,
    category: "Kebaplar",
    name: "Adana Beyti",
    price: 180,
    symbol: "₺",
    Image: "",
    description: "200gr",
  },
  {
    id: 52,
    category: "Kebaplar",
    name: "Çöp Şiş",
    price: 230,
    symbol: "₺",
    Image: "",
    description: "200gr",
  },
  {
    id: 53,
    category: "Kebaplar",
    name: "Lokum",
    price: 290,
    symbol: "₺",
    Image: "",
    description: "200gr",
  },
  {
    id: 54,
    category: "Kebaplar",
    name: "Şaşlık",
    price: 290,
    symbol: "₺",
    Image: "",
    description: "200gr",
  },
  {
    id: 55,
    category: "Dürümler",
    name: "Çöp Şiş Dürüm",
    price: "",
    symbol: "₺",
    Image: "",
    description: "(100gr) 120₺ I (150gr) 140₺ I (200gr)160₺",
  },
  {
    id: 56,
    category: "Dürümler",
    name: "Şeftali Dürüm",
    price: "",
    symbol: "₺",
    Image: "",
    description: "(150gr) 130₺ I (200gr) 160₺ I (250gr)170₺",
  },
  {
    id: 57,
    category: "Dürümler",
    name: "Köfde Dürüm",
    price: "",
    symbol: "₺",
    Image: "",
    description: "(150gr) 130₺ I (200gr) 160₺ I (250gr) 170₺",
  },
  {
    id: 58,
    category: "Dürümler",
    name: "Kuzu Ciğer Dürüm",
    price: "",
    symbol: "₺",
    Image: "",
    description: "(100gr) 130₺ I (150gr) 150₺ I (200gr) 185₺",
  },
  {
    id: 59,
    category: "Dürümler",
    name: "Tavuk Şiş Dürüm",
    price: "",
    symbol: "₺",
    Image: "",
    description: "(100gr) 105₺ I (150gr)120₺ I (200gr) 150₺",
  },
  {
    id: 60,
    category: "Dürümler",
    name: "Kuzu Şiş Dürüm",
    price: "",
    symbol: "₺",
    Image: "",
    description: "(100gr) 110₺ I (150gr) 130₺ I (200gr)150₺",
  },
  {
    id: 61,
    category: "Dürümler",
    name: "Adana Dürüm",
    price: "",
    symbol: "₺",
    Image: "",
    description: "(100gr) 100₺ I (150gr) 120₺ I (200gr)140₺",
  },
  {
    id: 62,
    category: "Diyet Menü",
    name: "Bİftek Izgara",
    price: "310",
    symbol: "₺",
    Image: "",
    description: "Dana Biftek, Haşlanmış Sebzeler ve Yoğurt",
  },
  {
    id: 63,
    category: "Diyet Menü",
    name: "Tavuk Izgara",
    price: "220",
    symbol: "₺",
    Image: "",
    description: "Tavuk Gögsü, Haşlanmış Sebzeler ve Yoğurt",
  },
  {
    id: 64,
    category: "Çocuk Menüsü",
    name: "Mini Pide(Kuşbaşılı)",
    price: "120",
    symbol: "₺",
    Image: "",
    description: "",
  },
  {
    id: 65,
    category: "Çocuk Menüsü",
    name: "Mini Tavuk Şiş + Cips",
    price: "115",
    symbol: "₺",
    Image: "",
    description: "",
  },
  {
    id: 66,
    category: "Rakı",
    name: "Tavuk Izgara",
    price: "90",
    symbol: "₺",
    Image: "",
    description: "",
  },
  {
    id: 67,
    category: "Rakı",
    name: "Sarı Zeybek",
    price: "",
    symbol: "₺",
    Image: "",
    description: "Sarı Zeybek₺35cl 255₺ 70 Cl 380₺",
  },
  {
    id: 68,
    category: "Rakı",
    name: "Hünkar Rakısı",
    price: "",
    symbol: "₺",
    Image: "",
    description: "70 Cl 475₺",
  },
  {
    id: 69,
    category: "Rakı",
    name: "Yeni Rakı Uzun Demleme",
    price: "",
    symbol: "₺",
    Image: "",
    description: "Kadeh 75₺ I 35 Cl 340₺ I 70 Cl 600₺",
  },
  {
    id: 70,
    category: "Rakı",
    name: "Beylerbeyi",
    price: "",
    symbol: "₺",
    Image: "",
    description: "Kadeh 75₺ 20 Cl 175₺ I 35 Cl 345₺ I 70 Cl 575₺",
  },
  {
    id: 71,
    category: "Rakı",
    name: "Efe Göbek",
    price: "90",
    symbol: "₺",
    Image: "",
    description: "Kadeh 75₺ I 35 Cl 175₺ I 35 Cl 345₺ I 70 Cl 575₺",
  },
  {
    id: 72,
    category: "Rakı",
    name: "Efe Gold",
    price: "",
    symbol: "₺",
    Image: "",
    description: "Kadeh 50₺ I 35 Cl 245₺ I 70 Cl 480₺",
  },
  {
    id: 73,
    category: "Rakı",
    name: "Tekirdağ Kavrulmuş",
    price: "",
    symbol: "₺",
    Image: "",
    description: "Kadeh 75₺ I 35 Cl 270 ₺ I 70 Cl 450 ₺",
  },
  {
    id: 74,
    category: "Rakı",
    name: "Ala",
    price: "",
    symbol: "₺",
    Image: "",
    description: "kadeh 75₺ I 20cl 275₺ I 35cl 375₺ I 70 Cl 620₺",
  },
  {
    id: 75,
    category: "Rakı",
    name: "Yeni Seri",
    price: "",
    symbol: "₺",
    Image: "",
    description: "kadeh 75₺ I 20cl 220₺ I 35cl 300₺ I 70 Cl 475₺",
  },
  {
    id: 76,
    category: "Rakı",
    name: "Yeni Rakı",
    price: "",
    symbol: "₺",
    Image: "",
    description: "kadeh 65₺ I 20cl 180₺ I 35cl 270₺ I 70 Cl 475₺",
  },
  {
    id: 77,
    category: "Rakı",
    name: "Tekirdağ Yeşil",
    price: "",
    symbol: "₺",
    Image: "",
    description: "Kadeh 75₺ I 35cl 245 ₺ I 70 Cl 375₺",
  },
  {
    id: 78,
    category: "Şaraplar",
    name: "Kadeh Şarap",
    price: "22",
    symbol: "₺",
    Image: "",
    description: "",
  },
  {
    id: 79,
    category: "Viski",
    name: "Blue Label",
    price: "9.500",
    symbol: "₺",
    Image: "",
    description: "70 Cl",
  },
  {
    id: 80,
    category: "Viski",
    name: "Jack Daniels",
    price: "",
    symbol: "₺",
    Image: "",
    description: "Kadeh 100 ₺ I 35 Cl 500₺ I 70 Cl 900₺",
  },
  {
    id: 81,
    category: "Viski",
    name: "Red Label",
    price: "",
    symbol: "₺",
    Image: "",
    description: "Kadeh 80₺ I 35 Cl 450 ₺ I 70 Cl 800₺",
  },
  {
    id: 82,
    category: "Viski",
    name: "Black Label",
    price: "",
    symbol: "₺",
    Image: "",
    description: "DRY kadeh 100₺ I 35 Cl 450₺ I 70 Cl 1200₺",
  },
  {
    id: 83,
    category: "Viski",
    name: "Chivas 25 Yıllık",
    price: "12.500",
    symbol: "₺",
    Image: "",
    description: "70cl",
  },
  {
    id: 84,
    category: "Viski",
    name: "Chivas 18 Yıllık",
    price: "3.200",
    symbol: "₺",
    Image: "",
    description: "70cl",
  },
  {
    id: 85,
    category: "Viski",
    name: "Chivas 12 Yıllık",
    price: "",
    symbol: "₺",
    Image: "",
    description: "35 Cl 800₺ I 70 Cl 1.500₺",
  },
  {
    id: 86,
    category: "Biralar",
    name: "Becks",
    price: "60",
    symbol: "₺",
    Image: "",
    description: "33cl",
  },
  {
    id: 87,
    category: "Biralar",
    name: "Efes Malt",
    price: "60",
    symbol: "₺",
    Image: "",
    description: "33cl",
  },
  {
    id: 88,
    category: "Biralar",
    name: "Miller",
    price: "60",
    symbol: "₺",
    Image: "",
    description: "33cl",
  },
  {
    id: 89,
    category: "İçecekler",
    name: "Cam Şişe Kola",
    price: "25",
    symbol: "₺",
    Image: "",
    description: "",
  },
  {
    id: 90,
    category: "İçecekler",
    name: "Redbull",
    price: "40",
    symbol: "₺",
    Image: "",
    description: "",
  },
  {
    id: 91,
    category: "İçecekler",
    name: "Büyük Su",
    price: "22",
    symbol: "₺",
    Image: "",
    description: "",
  },
  {
    id: 92,
    category: "İçecekler",
    name: "Küçük Su",
    price: "13",
    symbol: "₺",
    Image: "",
    description: "",
  },
  {
    id: 93,
    category: "İçecekler",
    name: "Küçük Şalgam",
    price: "16",
    symbol: "₺",
    Image: "",
    description: "",
  },
  {
    id: 94,
    category: "İçecekler",
    name: "Meyveli Soda",
    price: "16",
    symbol: "₺",
    Image: "",
    description: "",
  },
  {
    id: 95,
    category: "İçecekler",
    name: "Sade Soda",
    price: "15",
    symbol: "₺",
    Image: "",
    description: "",
  },
  {
    id: 96,
    category: "İçecekler",
    name: "Meyve Suları",
    price: "25",
    symbol: "₺",
    Image: "",
    description: "",
  },
  {
    id: 97,
    category: "İçecekler",
    name: "Ice Tea Limon",
    price: "25",
    symbol: "₺",
    Image: "",
    description: "",
  },
  {
    id: 98,
    category: "İçecekler",
    name: "Ice Tea Şeftali",
    price: "25",
    symbol: "₺",
    Image: "",
    description: "",
  },
  {
    id: 99,
    category: "İçecekler",
    name: "Şekersiz Kola",
    price: "25",
    symbol: "₺",
    Image: "",
    description: "",
  },
  {
    id: 100,
    category: "İçecekler",
    name: "Cola",
    price: "25",
    symbol: "₺",
    Image: "",
    description: "",
  },
];
